# Generated by Django 4.1.2 on 2022-10-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='load_valume',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('big', 'Big'), ('small', 'Small')], max_length=5),
        ),
    ]
