# Generated by Django 4.1.2 on 2022-10-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsys', '0002_alter_car_load_valume_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='national_code',
            field=models.BigIntegerField(),
        ),
    ]
