# Generated by Django 4.1.2 on 2022-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsys', '0003_alter_owner_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
