# Generated by Django 4.1.2 on 2022-10-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tsys', '0004_alter_roads_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnodes',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Tsys.roads'),
        ),
    ]
