# Generated by Django 4.1.2 on 2022-10-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsys', '0006_alter_roads_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allnodes',
            name='road',
        ),
        migrations.AddField(
            model_name='allnodes',
            name='road',
            field=models.ManyToManyField(null=True, to='Tsys.roads'),
        ),
    ]
